### ISSUE TITLE
KeyError: 'data' while running run_lstm_RGB.sh

### ISSUE THREAD

**Issue by hs3712993** [LisaAnne/lisa-caffe-public#2]
Traceback (most recent call last):
  File "sequence_input_layer.py", line 223, in forward
    new_result_data = [None]*len(self.thread_result['data'])
KeyError: 'data'
terminate called after throwing an instance of 'boost::python::error_already_set'
*** Aborted at 1441809596 (unix time) try "date -d @1441809596" if you are using GNU date ***
PC: @     0x7f3bd4f9d445 (unknown)
*** SIGABRT (@0x3f1000047b2) received by PID 18354 (TID 0x7f3bd64677c0) from PID 18354; stack trace: ***

I do not use the provided extract_frames.sh to extract rgb frames, and my rgb frames are stored in this way, rgb_home/action_name/video_name/000***.jpg
So I change the sequence_input_layer.py accordingly, as follows,

for ix, line in enumerate(f_lines):
      #video = line.split(' ')[0].split('/')[1]
      video = line
      l = int(line.split(' ')[1])
      #frames = glob.glob('%s%s/*.jpg' %(self.path_to_images, video))
      frames = glob.glob('%s%s/*.jpg' %(self.path_to_images, line))
      num_frames = len(frames)
      video_dict[video] = {}
      #video_dict[video]['frames'] = frames[0].split('.')[0] + '.%04d.jpg'
      video_dict[video]['frames'] = '%06d.jpg'

But when I run run_lstm_RGB.sh, I get the abolve error. What's wrong? Any one help me?

**Comment by GiovanniMancini** [comment]
I resolved rearranging the video archive as follows 

rgb_home/video_name/frame*.jpg

Regards

----- Messaggio originale -----
Da: "hongsong" <notifications@github.com>
Inviato: ‎10/‎09/‎2015 03:35
A: "LisaAnne/lisa-caffe-public" <lisa-caffe-public@noreply.github.com>
Oggetto: [lisa-caffe-public] KeyError: 'data' while running run_lstm_RGB.sh(#2)

Traceback (most recent call last):
File "sequence_input_layer.py", line 223, in forward
new_result_data = [None]len(self.thread_result['data'])
KeyError: 'data'
terminate called after throwing an instance of 'boost::python::error_already_set'
** Aborted at 1441809596 (unix time) try "date -d @1441809" if you are using GNU date ***
PC: @ 0x7f3bd4f9d445 (unknown)
*** SIGABRT (@0x3f1000047b2) received by PID 18354 (TID 0x7f3bd64677c0) from PID 18354; stack trace: ***
I do not use the provided extract_frames.sh to extract rgb frames, and my rgb frames are stored in this way, rgb_home/action_name/video_name/000***.jpg
So I change the sequence_input_layer.py accordingly, as follows,
for ix, line in enumerate(f_lines):
#video = line.split(' ')[0].split('/')[1]
video = line
l = int(line.split(' ')[1])
#frames = glob.glob('%s%s/.jpg' %(self.path_to_images, video))
frames = glob.glob('%s%s/.jpg' %(self.path_to_images, line))
num_frames = len(frames)
video_dict[video] = {}
#video_dict[video]['frames'] = frames[0].split('.')[0] + '.%04d.jpg'
video_dict[video]['frames'] = '%06d.jpg'
But when I run run_lstm_RGB.sh, I get the abolve error. What's wrong? Any one help me?

**Comment by gjyin91** [comment]
@hs3712993 I had the same problem,have you resolved it ? @GiovanniMancini your way does not work for me

**Comment by GoYchen** [comment]
I confront this issue today. I use pdb to debug sequence_input_layer.py and find that  
data_in = caffe.io.load_image(im_path) 
report ValueError: ValueErr...oat64.',) .
I am surer im_path is correct, I don't know how to fix this.

**Comment by lbj0411** [comment]
I also had the same problem with you, @hs3712993 @gjyin91..Did you resolved it yet?
